### ISSUE TITLE
Mssing file_get_contents in init.php

### ISSUE THREAD

**Issue by EXeduardo** [intaro/pinboard#105]
Hi!, I was unable to get configuration from paramaters.yml as is init.php, I had to add **file_get_contents** function when parsing to get it work, It could be an issue, congrats!.

`$app['params'] = Symfony\Component\Yaml\Yaml::parse(file_get_contents(__DIR__.'/../config/parameters.yml'));`

**Comment by Koc** [comment]
@EXeduardo have you run `composer install` first?
