### ISSUE TITLE
Can't create table 'pinba.ipm_pinba_tag_info_group_server_name' 

### ISSUE THREAD

**Issue by Aleks0305** [intaro/pinboard#106]
Hello!
environment: CentOS 6, mysql5.5, pinba from rpm mysql55-plugin-pinba-5.5.15-3.el6.x86_64.
When I try:
$ ./console migrations:migrate

I see:
  [PDOException]
  SQLSTATE[HY000]: General error: 1005 Can't create table 'pinba.ipm_pinba_tag_info_group_server_name' (errno: 140)

Tell me, please, in what may be a problem.
Thank you!

**Comment by muxx** [comment]
Hi.
> Before Pinboard installation you should already be installed pinba. Since the version 1.5 Intaro Pinboard requires Pinba 1.1 or higher.

**Comment by Aleks0305** [comment]
pinba installed and work but may be it version not 1.1...
