### ISSUE TITLE
php 5.6 PHP Strict Standards:  Non-static method Pinboard\\Utils\\Utils::getUserAccessHostsRegexp()

### ISSUE THREAD

**Issue by Aleks0305** [intaro/pinboard#107]
Hello!
I installed successfully pinboard, but always see in Apache logs the following errors. 
[Sat May 23 20:35:23 2015] [error] [client 192.168.1.1] PHP Strict Standards:  Non-static method Pinboard\\Utils\\Utils::getUserAccessHostsRegexp() should not be called statically in /var/www/html/pinboard/src/Pinboard/Controller/_before.php on line 16, referer: http://pinboard.dev/
[Sat May 23 20:35:23 2015] [error] [client 192.168.1.1] PHP Strict Standards:  Non-static method Pinboard\\Utils\\Utils::getUserAccessHostsRegexp() should not be called statically in /var/www/html/pinboard/src/Pinboard/Controller/index.php on line 16, referer: http://pinboard.dev/

However, no graphics are not displayed. 
[root@dev sites-available]# php -v
PHP 5.6.5 (cli) (built: Jan 22 2015 23:51:39)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

**Comment by abrgitlab** [comment]
Is there any solution?
