### ISSUE TITLE
Installation problem - migrations:migrate 

### ISSUE THREAD

**Issue by djkerya** [intaro/pinboard#111]
Problem when running this command:

# ./console migrations:migrate          
                                                                                                 
  [InvalidArgumentException]                                                                                      
  You have to specify a --db-configuration file or pass a Database Connection as a dependency to the Migrations.  
                                                                                                                  
migrations:migrate [--write-sql] [--dry-run] [--query-time] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]

Please help to figure out.
Can someone to explain what this step for?
How to pass database connection parameters to console?
Is there any other way to create schema?

**Comment by metfan** [comment]
Hello, 

I just update to v1.5.2 and I have the same problem.

**Comment by metfan** [comment]
@djkerya you can provide solve this problem easily:
- create db.php file on the root dir of you pinboard install
add this code (replace with your params):

```
<?php

return array(
    'driver'   => 'pdo_mysql',
    'dbname'   => 'your_databasename',
    'host'     => 'your_hostname',
    'user'     => 'user',
    'password' => 'password',

```

- then you can run this command:
```
./console  migrations:migrate  --db-configuration  ./db.php
```

**Comment by djkerya** [comment]
@metfan thanks, this helped. This step id done, but was still no data in the webinterface until I disabled apc cache in config (php 5.6 + apcu 4.0.7). Does anyone faced such problem?

**Comment by Koc** [comment]
Doctrine's bug, see https://github.com/doctrine/migrations/issues/266 . Already fixed, try `composer update`
