### ISSUE TITLE
Empty tables

### ISSUE THREAD

**Issue by pozharko** [intaro/pinboard#116]
I have pinba server, and I'm trying to add pinboard to it.
After installing pinboard, I see emty page (e.g. sites list is empty) 
Also most of ipm tables are empty

    mysql> select * from ipm_report_by_server_name;
    Empty set (0.00 sec)

while request table is not

    select count(*) from request;
    +----------+
    | count(*) |
    +----------+
    |     2930 |
    +----------+

**Comment by muxx** [comment]
Did you configure the cron task?

**Comment by pozharko** [comment]
What do you mean by configure? I runned following command (tried it one more time)

    sudo ./console register-crontab
    Defining crontab task...
    Please enter the frequency of data aggregating (frequency must be equal "pinba_stats_history" of the pinba engine config).
    Frequency (in minutes, default "15"): 
    Crontab task are defined successfully
    Please set parameter "aggregation_period" to value "PT15M" in config/parameters.yml

**Comment by muxx** [comment]
Why do you run this command under sudo? It is not require sudo. Run in the simple mode.

**Comment by pozharko** [comment]
first I tried without sudo, nothing changed

**Comment by pozharko** [comment]
Looks like problem is beacuse I don't have timestamp field in request table. What does this mean?

**Comment by pozharko** [comment]
pinba plugin version is correct
    
    mysql> SELECT * FROM information_schema.plugins where PLUGIN_NAME = 'PINBA';
    +-------------+----------------+---------------+----------------+---------------------+--------------------+------------------------+---------------+--------------------+----------------+-------------+
    | PLUGIN_NAME | PLUGIN_VERSION | PLUGIN_STATUS | PLUGIN_TYPE    | PLUGIN_TYPE_VERSION | PLUGIN_LIBRARY     | PLUGIN_LIBRARY_VERSION | PLUGIN_AUTHOR | PLUGIN_DESCRIPTION | PLUGIN_LICENSE | LOAD_OPTION |
    +-------------+----------------+---------------+----------------+---------------------+--------------------+------------------------+---------------+--------------------+----------------+-------------+
    | PINBA       | 1.1            | ACTIVE        | STORAGE ENGINE | 50621.0             | libpinba_engine.so | 1.4                    | Antony Dovgal | Pinba engine       | GPL            | ON          |
    +-------------+----------------+---------------+----------------+---------------------+--------------------+------------------------+---------------+--------------------+----------------+-------------+

but I see, that aggregation task uses it

        $sql = '
            INSERT INTO
                ipm_status_details (server_name, hostname, script_name, status, tags, tags_cnt, created_at)
            SELECT
                server_name, hostname, script_name, status, tags, tags_cnt, FROM_UNIXTIME(max(timestamp))
            FROM
                request
            WHERE
                status >= 500
            GROUP BY
                server_name, hostname, script_name
            LIMIT
                25
        ';

but structure of my request table is 

    mysql> describe request;
    +------------------+---------------+------+-----+---------+-------+
    | Field            | Type          | Null | Key | Default | Extra |
    +------------------+---------------+------+-----+---------+-------+
    | id               | int(11)       | NO   | PRI | 0       |       |
    | hostname         | varchar(32)   | YES  |     | NULL    |       |
    | req_count        | int(11)       | YES  |     | NULL    |       |
    | server_name      | varchar(64)   | YES  |     | NULL    |       |
    | script_name      | varchar(128)  | YES  |     | NULL    |       |
    | doc_size         | float         | YES  |     | NULL    |       |
    | mem_peak_usage   | float         | YES  |     | NULL    |       |
    | req_time         | float         | YES  |     | NULL    |       |
    | ru_utime         | float         | YES  |     | NULL    |       |
    | ru_stime         | float         | YES  |     | NULL    |       |
    | timers_cnt       | int(11)       | YES  |     | NULL    |       |
    | status           | int(11)       | YES  |     | NULL    |       |
    | memory_footprint | float         | YES  |     | NULL    |       |
    | schema           | varchar(16)   | YES  |     | NULL    |       |
    | tags_cnt         | int(11)       | YES  |     | NULL    |       |
    | tags             | varchar(1024) | YES  |     | NULL    |       |
    +------------------+---------------+------+-----+---------+-------+
    16 rows in set (0.00 sec)

**Comment by muxx** [comment]
Field `timestamp` added in pinba 1.1. In the install documentation there is the remark:
> Since the version 1.5 Intaro Pinboard requires Pinba 1.1 or higher.

**Comment by pozharko** [comment]
according 

    mysql> SELECT * FROM information_schema.plugins where PLUGIN_NAME = 'PINBA';
    +-------------+----------------+---------------+----------------+---------------------+--------------------+------------------------+---------------+--------------------+----------------+-------------+
    | PLUGIN_NAME | PLUGIN_VERSION | PLUGIN_STATUS | PLUGIN_TYPE    | PLUGIN_TYPE_VERSION | PLUGIN_LIBRARY     | PLUGIN_LIBRARY_VERSION | PLUGIN_AUTHOR | PLUGIN_DESCRIPTION | PLUGIN_LICENSE | LOAD_OPTION |
    +-------------+----------------+---------------+----------------+---------------------+--------------------+------------------------+---------------+--------------------+----------------+-------------+
    | PINBA       | 1.1            | ACTIVE        | STORAGE ENGINE | 50621.0             | libpinba_engine.so | 1.4                    | Antony Dovgal | Pinba engine       | GPL            | ON          |
    +-------------+----------------+---------------+----------------+---------------------+--------------------+------------------------+---------------+--------------------+----------------+-------------+

I have 1.1 version. If I'll downgrade to 1.4 this will fix the problem?

**Comment by muxx** [comment]
Yes.

**Comment by pozharko** [comment]
Thanks!
