### ISSUE TITLE
Вкладка с таймерами пустая

### ISSUE THREAD

**Issue by sychevsky** [intaro/pinboard#123]
Вкладка с таймерами пустая -  хотя в лайв режиме я вижу что таймеры есть, в чем может быть проблема?

**Comment by nitso** [comment]
+1 та же проблема, версия свежая.
По коду выяснил, что не заполняется таблица `ipm_pinba_tag_info_group_server_name`

Каким скриптом она должна заполняться? Греп нашел только селекты из этой таблицы.

**Comment by sychevsky** [comment]
Как я понял эта агреггирующая таблица - заполнятся должна самой пинбой

**Comment by muxx** [comment]
В таблицы `ipm_*` Pinboard складывает срезы данных из pinba-таблиц. Таймеры с замеры нужных участков нужно отправлять в определенном формате из-за ограничений pinba. В доках отражу позже, пример есть в презентации http://www.slideshare.net/muxx/pinboard-pinba-devconf-2014 (слайд 36).

**Comment by muxx** [comment]
Если у вас Symfony2, то можете использовать https://github.com/intaro/pinba-bundle, в нем есть `Stopwatch`, который оформит данные в нужном формате.

**Comment by nitso** [comment]
Правильно ли я понял, что заполнять таблицу `ipm_pinba_tag_info_group_server_name` нужно самим?

**Comment by nitso** [comment]
Точнее, их три:

    ipm_pinba_tag_info_group_server_server_name
    ipm_pinba_tag_info_group_server_name_hostname
    ipm_pinba_tag_info_group_server_server_name_hostname

**Comment by muxx** [comment]
https://github.com/intaro/pinboard/blob/master/src/Pinboard/Command/AggregateCommand.php#L356

Аггрегация из этих таблиц. В указанные таблицы pinba складывает таймеры. Вам нужно лишь отправлять эти таймеры из приложения.

**Comment by nitso** [comment]
В команде-агрегаторе:

    INSERT INTO ipm_tag_info
    SELECT ... FROM ipm_pinba_tag_info_group_server_server_name

И т.п. То есть, таблица `ipm_tag_info` - агрегирующая для данных из перечисленных таблиц. И данные в `ipm_tag_info` заносятся командой `Aggregate` по крону. Однако, таблицы-источники пустые и я не нашел никаких INSERT'ов в эти таблицы в проекте. 

Сам pinba-engine не работает с таблицами ipm_*.

**Comment by nitso** [comment]
Возможно, не хватает какого-то коммита с наполнением этих таблиц?

**Comment by muxx** [comment]
1. Вы шлете таймер из приложения
2. pinba принимает таймеры и пишет их в таблицы. Если вы посмотрите описание таблиц в базе, то увидите, что они типа `PINBA`
3. Pinboard складывает срезы из этих таблиц в `ipm_tag_info`.

Таблицы были созданы в миграциях: 
https://github.com/intaro/pinboard/blob/master/src/Pinboard/DoctrineMigrations/Version20140520164723.php

**Comment by nitso** [comment]
Да, действительно, тип `PINBA`.
Может быть тогда подскажите, в какую сторону копать, чтобы понять, почему туда не заносятся движком данные?

**Comment by muxx** [comment]
Вы таймеры шлете из приложения? Базовая информация по таймерам https://github.com/tony2001/pinba_engine/wiki/Basics#Timers

Сырые данные в таблице `timer` https://github.com/tony2001/pinba_engine/wiki/Raw-data-tables#timer_table

Если их там нет, то либо приложение не отправляет, либо пинба не принимает.

**Comment by nitso** [comment]
Таймеры отправляем, в таблице `timer` свежие записи пополняются. 
По урлу вроде `/timers/req_time/459300::2015-12-21%2014:29:26` данные переданных таймеров отображаются корректно. 
Но в таблицах `ipm_pinba_tag_info_*` пусто.

Обралил внимание, что в конфигурации репортов упоминаются следующие тэги:
`category`, `group`, `server`, `__server_name`, `__hostname`

Эти тэги нужно руками передавать в таймере, чтобы они попали в агрегацию?

`__server_name` и `__hostname` похожи на системные, но нигде в документации не нашел упоминания. Их тоже нужно передавать вручную?

**Comment by muxx** [comment]
Смотрели презентацию?

**Comment by sychevsky** [comment]
презентация приносит только частичное просветление - полное просветление наступает поле того как глянешь код коннектора под симфони

`$tags = array('category'=>'database', 'group'=>'TDb::connect', '__hostname'=>$_SERVER['HTTP_HOST'], '__server_name'=>$_SERVER['SERVER_NAME']);`

**Comment by nitso** [comment]
Еще немного пролил свет [Stopwatch.php](../blob/master/src/Pinboard/Stopwatch/Stopwatch.php). Сейчас попробуем отылать дополнительные тэги в таймере.

**Comment by muxx** [comment]
Ок, я отражу в документации попозже это. Костыли с `__*` тегами были введены из-за того, что в таблицах отчетов по таймерам нельзя нативно вытащить имя хоста и домена.

**Comment by nitso** [comment]
После добавления тэгов `category`, `__server_name`, `__hostname` инфа в `/server/{serverName}/{hostName}/timers` начала отображаться.

Спасибо за помощь!
