### ISSUE TITLE
Server Overview : File not found.

### ISSUE THREAD

**Issue by cedricbousmanne** [intaro/pinboard#128]
Hi just install a fresh build of pinboard. The main overview seems to look fine, but when I click on one of my site, I receive a "File not found." page.

Any idea? Thanks.

**Comment by muxx** [comment]
It seems that you maybe have a wrong nginx config.

**Comment by cedricbousmanne** [comment]
My bad, it was indeed a wrong nginx config within my fastcgi params. Thanks!
