### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by huoding** [intaro/pinboard#135]
when I execute: "console aggregate", show error:

SQLSTATE[01000]: Warning: 1265 Data truncated for column 'p90' at row 2

replay error by this sql:

INSERT INTO ipm_report_by_hostname (p90)
SELECT p90 FROM ipm_pinba_report_by_hostname_90_95_99;

show error when rows num of ipm_pinba_report_by_hostname_90_95_99 table greater than 1

**Comment by g3rhard** [comment]
@vladimirkudarev Perhaps you will be interested - https://github.com/intaro/pinboard/issues/139
