### ISSUE TITLE
Add tag support

### ISSUE THREAD

**Issue by muxx** [intaro/pinboard#5]
Requirements are in process.

**Comment by 1it** [comment]
Товарищи, удалось ли решить проблему?

> akademic commented on 22 Aug 2014

> Добрый день.
> Обновился сегодня на ветку tags и попробовал сделать console migration:migrate
> Вылезла такая ошибка:

> [PDOException]                                                                                                     
>   SQLSTATE[HY000]: General error: 1005 Can't create table 
>  'pinba.ipm_pinba_tag_info_group_server_name' (errno: 140)

**Comment by muxx** [comment]
Двумя комментариями ниже было объяснена причина проблема.

**Comment by stigout** [comment]
1it, добрый день!
Проблема в том, что при выполнении полного SQL-файла таблица request создается не полностью.

1. Удалите таблицу request
2. Посмотрите в SQL файле схему ее создания.
3. Выполните запрос на создание таблицы request, убедитесь что столбцы tags, tags_cnt созданы.

Удачи. Если что-то не получится, напишите.

**Comment by 1it** [comment]
Спасибо, но имел ввиду эту ошибку - SQLSTATE[HY000]: General error: 1005 Can't create table 'pinba.ipm_pinba_tag_info_group_server_name' (errno: 140)

Если я правильно понял надо собирать версию 1.1

**Comment by muxx** [comment]
Еще раз, я писал выше:
> У меня таймеры/теги работают корректно только на pinba из ветки devel, т.к. в master pinba бывает падает в момент аггрегации данных по таймерам.

Данная таблица типа pinba:
<pre>
            CREATE TABLE `ipm_pinba_tag_info_group_server_name` (
                    `tag1_value` varchar(64) DEFAULT NULL,
                    `tag2_value` varchar(64) DEFAULT NULL,
                    `req_count` int(11) DEFAULT NULL,
                    `req_per_sec` float DEFAULT NULL,
                    `hit_count` int(11) DEFAULT NULL,
                    `hit_per_sec` float DEFAULT NULL,
                    `timer_value` float DEFAULT NULL,
                    `timer_median` float DEFAULT NULL,
                    `ru_utime_value` float DEFAULT NULL,
                    `ru_stime_value` float DEFAULT NULL,
                    `index_value` varchar(256) DEFAULT NULL
                    ,`p90` float DEFAULT NULL,
                    `p95` float DEFAULT NULL,
                    `p99` float DEFAULT NULL
            ) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='tagN_info:group,__server_name::90,95,99'
</pre>
 и для ее создания требуется pinba c ветки `devel`, например, этой версии https://github.com/tony2001/pinba_engine/commit/5df9ba091e3ef531dfed1802d8afc3012e275002
