### ISSUE TITLE
No data on Timers tab

### ISSUE THREAD

**Issue by yefrem** [intaro/pinboard#91]
I've installed Pinboard's tags branch over master's DB, run migrations and try to use timers. They work for particular requests but Timers tab is empty. What can I check to understand what happens and if it's actually incorrect behaviour?

**Comment by avergizaev** [comment]
You should add tags '__hostname' and '__server_name' for your pinba-timers.
See https://github.com/intaro/pinboard/blob/master/src/Pinboard/Stopwatch/Stopwatch.php#L23

**Comment by yefrem** [comment]
@avergizaev unfortunately I can't check if it helps, don't have pinboard installation anymore but thanks for your response. Will close this old issue but maybe it will help someone or even me in a future.
